<!-- cities.inc -->
<!-- list of linked indymedia cities, for inclusion in all the indymedia sidebars -->
<br>
International<br>
<a href="http://www.indymedia.org">www.indymedia.org</a><br>
<br>
Australien<br>
<a href="http://www.melbourne.indymedia.org/">melbourne</a><br>
<a href="http://sydney.indymedia.org/">sydney</a><br>
<br>
Europa<br>
<a href="http://www.vaikuttava.net">finland</a><br>
<a href="http://barcelona.indymedia.org/">barcelona</a><br>
<a href="http://belgium.indymedia.org/">belgien</a><br>
<a href="http://germany.indymedia.org/">deutschland</a><br>
<a href="http://prague.indymedia.org/">tschechien</a><br>
<a href="http://www.indymedia.org.uk/">grossbritannien</a><br>
<a href="http://france.indymedia.org/">frankreich</a><br>
<a href="http://italy.indymedia.org/">italien</a><br>
<a href="http://austria.indymedia.org/">&ouml;sterreich</a><br>
<a href="http://russia.indymedia.org/">russland</a><br>
<a href="http://sweden.indymedia.org/">schweden</a><br>
<a href="http://switzerland.indymedia.org/">schweiz</a><br>
<br>
Kanada<br>
<a href="http://calgary.indymedia.org/">calgary</a><br>
<a href="http://hamilton.indymedia.org/">hamilton</a><br>
<a href="http://maritimes.indymedia.org/">maritimes</a><br>
<a href="http://montreal.indymedia.org/">montreal</a><br>
<a href="http://ontario.indymedia.org/">ontario</a><br>
<a href="http://quebec.indymedia.org/">québec</a><br>
<a href="http://vancouver.indymedia.org/">vancouver</a><br>
<a href="http://windsor.indymedia.org/">windsor</a><br>
<br>
Argentinien<br>
<a href="http://argentina.indymedia.org/">argentinien</a><br>
<br>
Brasilien<br>
<a href="http://brasil.indymedia.org/">brasilien</a><br>
<br>
Kolumbien<br>
<a href="http://colombia.indymedia.org/">kolumbien</a><br>
<br>
Kongo<br>
<a href="http://congo.indymedia.org/">kongo</a><br>
<!--<br >India<br>
<a href="http://india.indymedia.org/">india</a><br>-->
<br>
Israel<br>
<a href="http://indymedia.org.il/">israel</a><br>
<br>
Mexiko<br>
<a href="http://mexico.indymedia.org/">mexiko/D.F.</a><br>
<a href="http://chiapas.indymedia.org/">chiapas</a><br>
<br>
USA<br>
<a href="http://arizona.indymedia.org/">arizona</a><br>
<a href="http://atlanta.indymedia.org/">atlanta</a><br>
<a href="http://austin.indymedia.org/">austin</a><br>
<a href="http://boston.indymedia.org/">boston</a><br>
<a href="http://buffalo.indymedia.org/">buffalo</a><br>
<a href="http://chicago.indymedia.org/">chicago</a><br>
<a href="http://cleveland.indymedia.org/">cleveland</a><br>
<a href="http://hawaii.indymedia.org/">hawaii</a><br>
<a href="http://houston.indymedia.org/">houston</a><br>
<a href="http://la.indymedia.org/">la</a><br>
<a href="http://madison.indymedia.org/">madison</a><br>
<a href="http://maine.indymedia.org/">maine</a><br>
<a href="http://twincities.indymedia.org/">minneapolis/st. paul</a><br>
<a href="http://nyc.indymedia.org/">nyc</a><br>
<a href="http://nycap.indymedia.org/">new york capitol</a><br>
<a href="http://ohiovalleyimc.org/">ohio valley</a><br>
<a href="http://www.phillyimc.org/">philadelphia</a><br>
<a href="http://portland.indymedia.org/">portland</a><br>
<a href="http://richmond.indymedia.org/">richmond</a><br>
<a href="http://rockymountain.indymedia.org/">rocky mountain</a><br>
<a href="http://sf.indymedia.org/">san francisco bay area</a><br>
<a href="http://seattle.indymedia.org/">seattle</a><br>
<a href="http://urbana.indymedia.org/">urbana-champaign</a><br>
<a href="http://utah.indymedia.org/">utah</a><br>
<a href="http://vermont.indymedia.org/">vermont</a><br>
<a href="http://dc.indymedia.org/">dc</a><br>
<br>
IMC Projekte<br>
<a href="http://satellite.indymedia.org">satellite tv news</a><br>
<a href="http://print.indymedia.org/">print</a><br>
<a href="http://radio.indymedia.org/">radio</a><br>

<br>
IMC Process<br>
<a href="http://process.indymedia.org">process</a><br>
<a href="http://global.indymedia.org.au">discussion</a><br>
<a href="http://tech.indymedia.org">tech</a><br>
<a href="http://volunteer.indymedia.org/">volunteer</a><br>
<a href="http://lists.indymedia.org/">mailinglists</a><br>
<a href="http://www.indymedia.org/fbi">fbi/legal updates</a><br>
<br>

