		<p>
		<font size="-1">
		<a href="2001/05/2575.html"><b>summer of resistance</b></a>
		<br>
		
		
		<a href="http://www.genoa-g8.org/">
		19. bis 22.7:</a>
		&nbsp;
		<a href="http://italy.indymedia.org/">
		Italien
		</a>
		
		<br>
		G8 Genua, 
		<br>
		<br>
			
		<a href="http://www.50years.org/s28/call.html">
		28.9.
		</a>
		&nbsp;
		<a href="http://dc.indymedia.org/">
		USA
		</a>
		
		
		<br>
		Weltbank/IWF<br>
		Washington 
		<br>
		<br>
		
		<a href="http://www.noborder.org">
		<b>Grenzcamps</b>
		</a>
		<br>
		<a href="http://www.noborder.org/camps/ger/index.html">
		27. bis 5.8.</a>&nbsp;
		<a href="http://de.indymedia.org/">
		DE
		</a>  
		<br>
		Frankfurt/Main 
		 <br>
		 <br>
		 Global:<br>
		9. bis 15.11. WTO, Qatar<br>

		 <hr align="CENTER"  color="Green" noshade>
		
		<font size="-2">
		 mehr Termine:<br>
		 z.B. 
		 <a href="http://www.protest.net" target="_blank">weltweit</a> - 
		 <a href="http://radar.squat.net" target="_blank">europa</a> - 
		 <a href="http://stressfaktor.squat.net" target="_blank">berlin</a> 
		</font>
		</font>
		</p>
