		<a href="http://www.nadir.org/nadir">nadir</a><br>
		<a href="http://www.ainfos.ca/de">a-infos</a><br>
		<a href="http://www.squat.net">squat.net</a><br>
		<a href="http://www.linkeseite.de">linkeseite</a><br>
		<a href="http://gib.squat.net">gegeninformationsb&uuml;ro</a><br>
		<a href="http://www.info.partisan.net">partisan.net</a><br>
		<a href="http://www.dir-info.de/nachrichten/">DIR</a><br>
