log4j.rootLogger= WARN, A1
log4j.logger.Utility= INFO, UtilityA
log4j.logger.Global= INFO, GlobalA
log4j.logger.Servlet= INFO, ServletA
log4j.logger.Database= INFO, DatabaseA
log4j.logger.Entity= INFO, EntityA
log4j.logger.Media= INFO, MediaA
log4j.logger.Producer= INFO, ProducerA
log4j.logger.ServletModule= INFO, ServletModuleA
log4j.logger.Module= INFO, ModuleA
log4j.logger.Localizer= INFO, LocalizerA 
log4j.logger.Generator= INFO, GeneratorA
log4j.logger.PDFGenerator= INFO, PDFGeneratorA
log4j.logger.AdminUsage= INFO, AdminUsageA
log4j.additivity.AdminUsage=false

log4j.appender.A1=org.apache.log4j.ConsoleAppender
log4j.appender.A1.layout=org.apache.log4j.PatternLayout
log4j.appender.A1.layout.ConversionPattern=%d [%p] %c %x %m%n

log4j.appender.DatabaseA=org.apache.log4j.RollingFileAppender
log4j.appender.DatabaseA.File=${log.home}/database.log
log4j.appender.DatabaseA.layout=org.apache.log4j.PatternLayout
log4j.appender.DatabaseA.layout.ConversionPattern=%d [%p] %c %x %m%n

log4j.appender.EntityA=org.apache.log4j.RollingFileAppender
log4j.appender.EntityA.File=${log.home}/entity.log
log4j.appender.EntityA.layout=org.apache.log4j.PatternLayout
log4j.appender.EntityA.layout.ConversionPattern=%d [%p] %c %x %m%n

log4j.appender.ServletA=org.apache.log4j.RollingFileAppender
log4j.appender.ServletA.File=${log.home}/servlet.log
log4j.appender.ServletA.layout=org.apache.log4j.PatternLayout
log4j.appender.ServletA.layout.ConversionPattern=%d [%p] %c %x %m%n

log4j.appender.MediaA=org.apache.log4j.RollingFileAppender
log4j.appender.MediaA.File=${log.home}/media.log
log4j.appender.MediaA.layout=org.apache.log4j.PatternLayout
log4j.appender.MediaA.layout.ConversionPattern=%d [%p] %c %x %m%n

log4j.appender.ProducerA=org.apache.log4j.RollingFileAppender
log4j.appender.ProducerA.File=${log.home}/producer.log
log4j.appender.ProducerA.layout=org.apache.log4j.PatternLayout
log4j.appender.ProducerA.layout.ConversionPattern=%d [%p] %c %x %m%n

log4j.appender.ServletModuleA=org.apache.log4j.RollingFileAppender
log4j.appender.ServletModuleA.File=${log.home}/servletmodule.log
log4j.appender.ServletModuleA.layout=org.apache.log4j.PatternLayout
log4j.appender.ServletModuleA.layout.ConversionPattern=%d [%p] %c %x %m%n

log4j.appender.ModuleA=org.apache.log4j.RollingFileAppender
log4j.appender.ModuleA.File=${log.home}/module.log
log4j.appender.ModuleA.layout=org.apache.log4j.PatternLayout
log4j.appender.ModuleA.layout.ConversionPattern=%d [%p] %c %x %m%n

log4j.appender.LocalizerA=org.apache.log4j.RollingFileAppender
log4j.appender.LocalizerA.File=${log.home}/localizer.log
log4j.appender.LocalizerA.layout=org.apache.log4j.PatternLayout
log4j.appender.LocalizerA.layout.ConversionPattern=%d [%p] %c %x %m%n

log4j.appender.GeneratorA=org.apache.log4j.RollingFileAppender
log4j.appender.GeneratorA.File=${log.home}/template.log
log4j.appender.GeneratorA.layout=org.apache.log4j.PatternLayout
log4j.appender.GeneratorA.layout.ConversionPattern=%d [%p] %c %x %m%n

log4j.appender.GlobalA=org.apache.log4j.RollingFileAppender
log4j.appender.GlobalA.File=${log.home}/global.log
log4j.appender.GlobalA.layout=org.apache.log4j.PatternLayout
log4j.appender.GlobalA.layout.ConversionPattern=%d [%p] %c %x %m%n

log4j.appender.UtilityA=org.apache.log4j.RollingFileAppender
log4j.appender.UtilityA.File=${log.home}/global.log
log4j.appender.UtilityA.layout=org.apache.log4j.PatternLayout
log4j.appender.UtilityA.layout.ConversionPattern=%d [%p] %c %x %m%n

log4j.appender.PDFGeneratorA=org.apache.log4j.RollingFileAppender
log4j.appender.PDFGeneratorA.File=${log.home}/pdf.log
log4j.appender.PDFGeneratorA.layout=org.apache.log4j.PatternLayout
log4j.appender.PDFGeneratorA.layout.ConversionPattern=%d [%p] %c %x %m%n

log4j.appender.AdminUsageA=org.apache.log4j.RollingFileAppender
log4j.appender.AdminUsageA.File=${log.home}/adminusage.log
log4j.appender.AdminUsageA.layout=org.apache.log4j.PatternLayout
log4j.appender.AdminUsageA.layout.ConversionPattern=%d %m%n

