# this file is used when the key is not found in any other bundle for the
# selected language. so we use it to store information that is not language
# specific but IMC specific
# this should maybe be at some other place (in the config file)

### imc information
imc.name=indymedia.de
imc.shortname=imc-germany
imc.contact-email.address=imc-germany@indymedia.org
imc.contact-email.name=Redaktionsliste
imc.tech-email.address=imc-germany-tech@indymedia.org
imc.tech-email.name=imc-germany-tech@indymedia.org
imc.public-email.address=imc-germany-public@lists.indymedia.org
imc.public-email.name=imc-germany-public@lists.indymedia.org